export const INC_COUNT = 'INC_COUNT'
export const DEC_COUNT = 'DEC_COUNT'
export const ADD_COUNT = 'ADD_COUNT'
export const MUL_COUNT = 'MUL_COUNT'
export const SUB_COUNT = 'SUB_COUNT'
export const DIV_COUNT = 'DIV_COUNT'